#  more config options in the docs
#  https://openapi-generator.tech/docs/generators
enumUnknownDefaultCase: true
# generator dart Api required
# 与pubspec路径要一致
pubName: open_api_yaml
useEnumExtension: true
# generator typescript Api required
npmName: person-api-test-rxjs
# generator go Api required
packageName: person-api-test-go